spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

server:
  port: 8080
  servlet:
    encoding:
      force-response: true
